# This is a basic workflow to help you deploy an ADF ARM template to a higher environmentss

# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

name: Deploy to QA and Prod
on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:
env:
  ARMTemplate: "./devcicdtesta/ARMTemplateForFactory.json"
  ARMParameter: "./devcicdtesta/ARMTemplateParametersForFactory.json"
jobs:
    deploy-to-qa:
      runs-on: ubuntu-latest
      environment: QA
      name: 'This deploys to QA'
      steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{secrets.AZURE_CREDENTIALS}}
      
      - name: Install Az PowerShell module
        run: if('${{ inputs.skipAzModuleInstallation }}' -ne 'true') { Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force }
        shell: pwsh
    
      - name: Run Pre-deployment script
        uses: azure/powershell@v1
        with: |
          ./PrePostDeploymentScript.ps1 `
                -armTemplate "devcicdtesta/ARMTemplateForFactory.json" `
                -ResourceGroupName "${{vars.Azure_RG}}" `
                -DataFactoryName "${{vars.factory_name}}" `
                -predeployment $true `
                -deleteDeployment $false
