# This is a basic workflow to help you deploy an ADF ARM template to a higher environments

# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

name: Deploy to QA and Prod
on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:


jobs:
    deploy-to-qa:
      runs-on: ubuntu-latest
      environment: QA
      env:
        Credentials : ${{secrets.AZURE_CREDENTIALS}}
        Azure_RG : ${{secrets.AZURE_RG}}
        AzureBlobStorage1_connectionString: ${{vars.AzureBlobStorage1_connectionString}}
        factory_name: ${{vars.factory_name}}
      name: 'This deploys to QA'
      steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: $Credentials

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1.0.6
        with:
          # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
          scope: 'resourcegroup'
          # Target resource group of the deployment.
          resourceGroupName: $Azure_RG
          # Specify the path to the ADF ARM template. In this scenario, the workflow is in the same branch, 
          # hence we only add the folder and arm template name to the path
          template: ./devcicdtesta/ARMTemplateForFactory.json
          parameters: ./devcicdtesta/ARMTemplateParametersForFactory.json 
            AzureBlobStorage1_connectionString=$AzureBlobStorage1_connectionString
            factoryName=$factory_name

          # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
          deploymentMode: Incremental

    deploy-to-prod:
      runs-on: ubuntu-latest
      environment: prod
      env:
        Credentials : ${{secrets.AZURE_CREDENTIALS}}
        Azure_RG : ${{secrets.AZURE_RG}}
        AzureBlobStorage1_connectionString: ${{vars.AzureBlobStorage1_connectionString}}
        factory_name: ${{vars.factory_name}}
      name: 'This deploys to Prod'
      needs: deploy-to-qa
      steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: $Credentials

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1.0.6
        with:
          # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
          scope: 'resourcegroup'
          # Target resource group of the deployment.
          resourceGroupName: $Azure_RG
          # Specify the path to the ADF ARM template. In this scenario, the workflow is in the same branch, 
          # hence we only add the folder and arm template name to the path
          template: ./devcicdtesta/ARMTemplateForFactory.json
          parameters: ./devcicdtesta/ARMTemplateParametersForFactory.json 
            AzureBlobStorage1_connectionString=$AzureBlobStorage1_connectionString
            factoryName=$factory_name

          # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
          deploymentMode: Incremental
