# This is a basic workflow to help you deploy an ADF ARM template to a higher environmentss

# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

name: Deploy to QA and Prod
on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:
env:
  ARMTemplate: "./devcicdtesta/ARMTemplateForFactory.json"
  ARMParameter: "./devcicdtesta/ARMTemplateParametersForFactory.json"
jobs:
    deploy-to-qa:
      runs-on: ubuntu-latest
      environment: QA
      name: 'This deploys to QA'
      steps:
      - uses: actions/checkout@v3
      
      - name: Run Post-deployment script
        shell: pwsh
        run: |
            $secrets = '${{secrets.AZURE_CREDENTIALS}}'
            write-output $secret
                
