#testh
name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy_qa:
        runs-on: ubuntu-latest
        env:
          QA_VARIABLE_1: ${{ env.factory_name }}
        steps:
        - name: Print QA Variable
          run: echo $QA_VARIABLE_1
