#testh
name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy_qa:
        runs-on: ubuntu-latest
        environment: QA
        steps:
        - name: Print QA Variable
          run: echo ${{var.factory_name}}        
  deploy_prod:
    runs-on: ubuntu-latest
    environment: prod
    env:
        PROD_VARIABLE_1: ${{ vars.factory_name }}
    steps:
      - name: Print Prod Variable
        run: echo $PROD_VARIABLE_1
