#testh
name: My Workflow

on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:




jobs:
  deploy_qa:
        runs-on: ubuntu-latest
        env:
          QA_VARIABLE_1: ${{ env.vars.factory_name }}
        steps:
        - name: Print QA Variable
          run: echo QA_VARIABLE_1
        
  deploy_prod:
    runs-on: ubuntu-latest
    env:
        PROD_VARIABLE_1: ${{ env.vars.factory_name }}
    steps:
      - name: Print Prod Variable
        run: echo PROD_VARIABLE_1
